#pragma once



enum ValueType{

    INT_VAL, DOUBLE_VAL, FLOAT_VAL, STRING_VAL, CHAR_VAL, BOOL_VAL, NONE_VAL, FUNC_DEC_VAL, INT_ARR_VAL, DOUBLE_ARR_VAL, FLOAT_ARR_VAL, STRING_ARR_VAL, CHAR_ARR_VAL

};
